language: rust

sudo: false
dist: trusty
addons:
    apt:
        packages:
            - libcurl4-openssl-dev
            - libelf-dev
            - libdw-dev
            - binutils-dev
            - libiberty-dev
            - gcc-multilib

os:
    - linux
    - osx

rust:
    - 1.17.0
    - beta
    - nightly

matrix:
    allow_failures:
        - rust: beta

install:
    - if [ "$TRAVIS_OS_NAME" = 'linux' ]; then OS=unknown-linux-gnu; else OS=apple-darwin; fi
    - rustup target add i686-$OS

script:
    - cargo test --no-default-features
    - cargo test
    - if [ "$TRAVIS_RUST_VERSION" = 'nightly' ]; then cargo bench --features=bench; fi
    - cargo test --target i686-$OS

after_success:
    - cargo install cargo-kcov
    - cargo kcov --print-install-kcov-sh | bash
    - cargo kcov --coveralls

